name: Annoucement Notify

on:
  discussion:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send DingGroup1 Anouncement Notify
        uses: zcong1993/actions-ding@master
        if: github.event.discussion.category.name == 'Announcements'
        with:
          dingToken: ${{ secrets.DING_GROUP_TOKEN }}
          secret: ${{ secrets.DING_GROUP_SIGN }}
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "title": "Qiankun News",
                  "text": "# qiankun [${{github.event.discussion.title}}](${{github.event.discussion.html_url}}) 新闻播报📢\n${{github.event.discussion.body}}",
              }
            }
